### ISSUE TITLE
CircleCI Ruby Pubsub test/generation is failing

### ISSUE THREAD

**Issue by andreamlin** [googleapis/gapic-generator#2503] opened 2019-01-10 01:05 UTC
Possibly due to https://github.com/googleapis/google-cloud-ruby/pull/2782#discussion_r246550700.

Sample failure log: https://circleci.com/gh/googleapis/gapic-generator/13089.

**Comment by andreamlin** [comment] 2019-01-10 02:35
cc @blowmage

**Comment by eoogbe** [comment] 2019-02-11 18:51
@jbolinger What's the status of this?

**Comment by jbolinger** [comment] 2019-02-11 18:55
This is blocked by https://github.com/protocolbuffers/protobuf/issues/5584

Yoshi, et al have post-processing workarounds but this is a good test for the namespace feature so I don't think we should workaround the root cause for our tests.

**Comment by blowmage** [comment] 2019-02-11 19:01
I somehow missed the notification for this over the weekend. My apologies.

As Joe says, we are working around this for the time being, including releasing a google-cloud-pubsub gem with the workaround last week.

**Comment by andreamlin** [comment] 2019-02-15 17:31
(Before this issue gets closed, we should re-instate the Ruby test in CircleCI)

**Comment by jbolinger** [comment] 2019-02-15 21:29
I sent an upstream patch to fix this: https://github.com/protocolbuffers/protobuf/pull/5735

However, even if they take it soon, it's probably going to be awhile before it gets released.

**Comment by blowmage** [comment] 2019-02-15 21:38
That's awesome! Thanks!

**Comment by noahdietz** [comment] 2019-02-25 18:46
@jbolinger can you provide an update here? I see there are some recent comments on the PR you opened.

1. Have the tests been re-instated following the workaround release?
2. Can we close this issue once your aforementioned PR is merged? Rather than wait for a release.

**Comment by jbolinger** [comment] 2019-02-25 19:07
We cannot reinstate the tests unless we apply a similar workaround or wait for a release with the fix. I suspect it's going to be awhile before a fix is released.

I think it may be better to lower the priority of this rather than close it, so we know the test isn't running. We're not making any changes to this Ruby generator here so fixing this test is not that important IMHO.

**Comment by noahdietz** [comment] 2019-03-01 18:54
Lowering to P2 as workarounds have unblocked the affected GAPIC and the upstream fix is in flight.

**Comment by vchudnov-g** [comment] 2019-08-05 21:21
@jbolinger Any updates on this? We're out of SLO.

**Comment by jbolinger** [comment] 2019-08-05 22:05
I think we should close it at this point given the progress on https://github.com/googleapis/gapic-generator-ruby. If it's still an issue it'll get raised during the migration and we've been able to work around it here fairly easily.

**Closed by jbolinger** 2019-08-05 22:05 UTC
Labels: :rotating_light:, Lang: Ruby, priority: p2, type: bug
