### ISSUE TITLE
proto libraries have dependency on api-common

### ISSUE THREAD

**Issue by anuraaga** [googleapis/gapic-generator#2648] opened 2019-03-25 03:29 UTC
I'm not sure if this is the correct repository for filing this issue, please let me know if it isn't.

I've found that proto libraries (e.g., [proto-google-cloud-trace-v2](https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-cloud-trace-v2/0.49.0)) depend on [api-common](https://mvnrepository.com/artifact/com.google.api/api-common/1.7.0).

I think proto libraries should only have dependencies on `protobuf-java`, not on `api-common` because `api-common` is only used by the cloud Java libraries when consuming the stubs, but the stubs should still be usable independent of them. Does it make sense to remove the dependency on `api-common` from proto libraries?

**Comment by michaelbausor** [comment] 2019-03-25 16:23
@andreamlin @vam-google can you comment on this issue? If it is possible, it seems like a good idea.

**Comment by vam-google** [comment] 2019-03-25 18:52
@michaelbausor @anuraaga 
1) This is the correct repository to filing the issue. Thank you.
2) `proto-google-cloud-trace-v2` has to depend on api-common protos, but we generate many clients which do not have to depend (but still depend (see item 5 for details)).
3) Every library which uses resource names feature has to depend on `api-common` because of `com.google.api.pathtemplate.PathTemplate` and `com.google.api.resourcenames.ResourceName` classes. Specifically `proto-google-cloud-trace-v2` [depends on them](https://github.com/googleapis/google-cloud-java/blob/master/google-api-grpc/proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/ProjectName.java#L17).
4) In other words, `proto-google-cloud-*` contain not only generated proto stubs, but also (for some libraries) the generated resource name classes, and those classes depend on `api-common`. Those classes generated not by protobuf (i.e. `protoc` binary), but by gapic-generator (that is why this is the correct repository for the issue).
3) The root cause of the problem of generating an unnecessary dependency on `api-common` is here: [JavaPackageTransformer](https://github.com/googleapis/gapic-generator/blob/master/src/main/java/com/google/api/codegen/packagegen/java/JavaPackageTransformer.java#L71). The `SERVICES_WITH_NO_RESOURCE_NAMES` is a legacy thing which has never been updated (while should have been). `api-common` is needed in case if resource names are used.

We should stop generating api-common dependency for libraries, which do not need it, but we can't remove dependency on api-common library for others (maybe `proto-` prefix for the package is confusing, but it does not imply that those classes are solely proto generated stubs and nothing else).

**Comment by anuraaga** [comment] 2019-03-26 02:53
Thanks I didn't notice the `ProjectName` java class in the library and indeed got tricked by the prefix `proto-`.

The main reason I wondered about this is because `api-common` depends on Guava - due to recent breaking changes in Guava, it can cause some tricky dependency hell in libraries that use these protos but also have to support older JVMs, etc. If it's possible to remove that dependency, that could be nice, but at least it also seems reasonable to exclude the `api-common` transitive dependency as long as we don't use the resource name stuff.

**Comment by andreamlin** [comment] 2019-03-28 15:54
ack

**Comment by miraleung** [comment] 2020-06-01 19:43
Closing as obsolete.

**Closed by miraleung** 2020-06-01 19:43 UTC
Labels: Lang: Java, dependencies, priority: p2
