### ISSUE TITLE
[Ruby] Generated docs for speech class uses "gapic-toolkit" as a sample bucket name

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2122] opened 2018-06-27 21:31 UTC
When generating google-cloud-speech, the following is an excerpt of the generated module documentation for `Google::Cloud::Speech`:

```ruby
    # ### Preview
    # #### SpeechClient
    # ```rb
    # require "google/cloud/speech"
    #
    # speech_client = Google::Cloud::Speech.new
    # language_code = "en-US"
    # sample_rate_hertz = 44100
    # encoding = :FLAC
    # config = {
    #   language_code: language_code,
    #   sample_rate_hertz: sample_rate_hertz,
    #   encoding: encoding
    # }
    # uri = "gs://gapic-toolkit/hello.flac"
    # audio = { uri: uri }
    # response = speech_client.recognize(config, audio)
    # ```
```

Note the use of `gapic-toolkit` as a sample bucket name. We should not use this name because its specificity may confuse users into thinking they must use that particular bucket. Previously it was just called `bucket-name` which seems more reasonable.

**Comment by jbolinger** [comment] 2018-06-27 22:02
Duplicate of #2106

**Closed by jbolinger** 2018-06-27 22:02 UTC
