### ISSUE TITLE
[Ruby] Product documentation link in generated README is sometimes incorrect

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2196] opened 2018-08-03 20:55 UTC
Currently the generated README for redis includes this link used for product documentation:

```md
[Product Documentation]: https://cloud.google.com/redis
```

This page doesn't exist. It turns out the correct link happens to be https://cloud.google.com/memorystore but I don't see how it's possible to interpret that unless there's a field in the proto somewhere. Or maybe there needs to be a field in the artman yaml. Either way, we should either have a way to generate a correct link, or omit it altogether.

**Comment by jbolinger** [comment] 2018-08-03 21:45
I don't think there's any way to do this now.  However, I'll send you some info offline about future plans that would enable things like this.

**Comment by vchudnov-g** [comment] 2018-11-07 19:02
@jbolinger Update? We're out of SLO here.

**Comment by jbolinger** [comment] 2018-11-07 19:09
@vchudnov-g We are planning to address all these P2/yoshi/ruby issues as we make progress on https://github.com/googleapis/gapic-generator-ruby so there won't be any updates here, but I'd like to keep them open until we've addressed it there.

**Comment by vchudnov-g** [comment] 2018-11-08 20:20
Fine, but consider moving the issues there so there's less but clearer work for the on-call in enforcing SLOs.

**Comment by noahdietz** [comment] 2019-02-25 18:54
Hi, on-call coming around to this issue! Can we move this or close it as a dupe of #1811 ?

**Comment by noahdietz** [comment] 2019-08-14 18:35
@jbolinger @dazuma  has this issue been moved to the gapic-generator-ruby repo? If it won't be fixed here, the issue should be tracked where it'll be fixed. This issue will eventually be out of SLO, especially if folks aren't tracking it where it's actually going to be fixed. I'm happy to open the issue myself if preferred.

**Comment by jbolinger** [comment] 2019-08-14 19:34
It's not really relevant in gapic-generator-ruby and we are not planning to fix it here, so I'll close this out.

**Closed by jbolinger** 2019-08-14 19:34 UTC
Labels: Lang: Ruby, Priority: P3, type: bug, yoshi
