### ISSUE TITLE
[Python] Remove templating of nox.py from generation.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2360] opened 2018-10-10 18:28 UTC
Nox has brought updates since templating the nox.py files. google-cloud-python has been brought forward, but the templated nox.py from GAPIC also needs to be updated.

**Comment by vchudnov-g** [comment] 2018-11-12 18:19
@lukesneeringer Any updates? Feel free to update labels as appropriate.

**Comment by andreamlin** [comment] 2018-11-26 20:03
@crwilcox Would you mind providing examples for how the nox.py templates should be updated?

**Comment by crwilcox** [comment] 2018-11-29 00:49
We started providing the template from synthtool https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/noxfile.py.j2

So, really we don't use the current one. If it is useful for other users (it may very well be) you could use this as a template. Otherwise it may be reasonable for the generator to not provide this at all?

**Comment by lukesneeringer** [comment] 2018-11-30 16:52
I am happy to just remove it.

Question: Last I checked, the latest version of nox still has to be installed with `--pre`. Any plans to rip off the bandaid on that?

**Comment by jbolinger** [comment] 2018-12-10 18:21
@lukesneeringer Any updates on this one?

**Comment by landrito** [comment] 2019-01-02 17:57
@lukesneeringer Any updates?

**Comment by vam-google** [comment] 2019-01-09 17:51
@lukesneeringer I'm to reassign this to myself. This is relevant to bazel work as well (the less files we need to generate with bazel the better, so reducing the number of expected files in the output makes bazel integration easier in terms of feature parity with artman). Please let me know if you want to keep it assigned to yourself.

**Comment by jbolinger** [comment] 2019-03-18 16:58
@vam-google any updates on this one?

**Comment by vam-google** [comment] 2019-04-01 17:09
Bazel support for Python generation was deprioritized in favor of java convergence. I'll get back to this once Java convergence project is completed.

**Comment by busunkim96** [comment] 2019-04-30 21:50
I think we'd prefer to simply remove `nox.py`, since we add `noxfile.py` via synthtool.

**Comment by vchudnov-g** [comment] 2019-05-21 00:00
@vam-google Could you provide an update?

**Comment by vchudnov-g** [comment] 2019-08-05 21:08
@vam-google Could you provide an update, reprioritize, or re-assign (maybe @hzyi-google ?). We're out of SLO on this issue.

**Comment by vchudnov-g** [comment] 2019-08-05 21:10
(Ah, nm, not technically out of SLO since it's not a bug but a FR. But still, an update would be good.)

**Comment by software-dov** [comment] 2019-10-14 18:08
@vam-google Any update?

**Comment by software-dov** [comment] 2019-10-24 17:26
@vam-google I remember that python bazel gapic support landed recently; does that mean this bug is now closable?

**Comment by software-dov** [comment] 2019-11-04 22:22
There's been no action on this in a year and no obvious sign that it's a problem. Closing.

**Closed by software-dov** 2019-11-04 22:22 UTC
Labels: Lang: Python, Priority: P1, type: feature request, yoshi
