### ISSUE TITLE
Don't allow inconsistent method timeout values for retryable methods

### ISSUE THREAD

**Issue by kmjung** [googleapis/gapic-generator#2780] opened 2019-05-20 17:40 UTC
GAPIC allows per-method timeout values to be specified in two places for retryable methods:

https://github.com/googleapis/gapic-generator/blob/master/src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml#L65
https://github.com/googleapis/gapic-generator/blob/master/src/test/java/com/google/api/codegen/testsrc/common/library_gapic.yaml#L86

My understanding is that, when retry settings are specified, the method-level timeout annotation is ignored. My team ran into an issue where we set the method-level value but not the values in the retry settings, leading to an unexpected deadline value. This could be avoided in the future either by requiring that the timeout values from the method and the retry settings be consistent, or by rejecting timeout annotations on methods for which retry settings are specified.

**Comment by kmjung** [comment] 2019-05-20 17:42
cc: @tswast

**Comment by hzyi-google** [comment] 2019-07-08 17:36
Hey @noahdietz you are the only person I know who is working on move retry configs out of gapic config. Would you be able to take a look?

**Comment by noahdietz** [comment] 2019-07-08 17:59
Thanks @hzyi-google yes, I can take a look at this. In fact, I opened another, slightly more specific issue as #2866 relating to the addition of gRPC ServiceConfig for retries w/GAPIC config v2. I was going to bring this to the team soon.

@kmjung thanks for this! I have a few questions.

1. What language(s) were you seeing issues with?
2. Do you have a link to the offending configuration?

 > My team ran into an issue where we set the method-level value but not the values in the retry settings, leading to an unexpected deadline value.

To clarify (please correct me), a named retry params config (e.g. `create_methods_retry_params`) that **did not** have a timeout specified was assigned to a method, a method-level `timeout_millis` was defined for said method, and an unexpected deadline (presumably **not** based on the value you set at the method-level) was experienced?

> or by rejecting timeout annotations on methods for which retry settings are specified.

This is the intended behavior based on the [config proto comments for `timeout_millis`](https://github.com/googleapis/gapic-generator/blob/c04c0061321546132563f6f3f6679e32191d5359/src/main/proto/com/google/api/codegen/v2/config_v2.proto#L188-L189) (your aforementioned understanding of the behavior is aligned). 

Clarification of the unexpected behavior you experienced will help me figure out the delta. AFAIK, many languages ignore the method-level `timeout_millis` entirely (listed in the aforementioned proto field comment).

I am working to migrate our retry configuration to gRPC's format as part of our GAPIC config v2 development. The work is parked in #2859.

**Comment by kmjung** [comment] 2019-07-10 17:43
In our case, the language in question was Python. Here's a link to the change that fixed the issue for us: https://github.com/googleapis/googleapis/commit/64f0053af0c24d817ec44278c8b4513f6cfd77ff#diff-dd4c7b3087025d4de8e2df1eb8473bcd

You can also check out e.g. https://github.com/googleapis/google-cloud-python/commit/583638be52d2718658c1ce0329a1e0b449ce6d5d#diff-0bb434bca16c242aceb62925b9b7e8f8

**Comment by hkdevandla** [comment] 2020-06-03 20:46
@noahdietz , can you take a look at this and see if this is still relevant?

**Comment by noahdietz** [comment] 2020-06-03 21:03
This is essentially fixed by moving to grpc_service_config, which we will be working through for monolith languages (micro-generators are already using this new config). There is only one place to set a timeout on an RPC in that config and `gapic-generator` will set that timeout in the generated client such that there is a single RPC made with that exact deadline. We can probably close this because we won't be adding any extra enforcement of what value is set where in the GAPIC config (because it wont be used for this anymore).

**Closed by noahdietz** 2020-06-03 21:03 UTC
Labels: priority: p2, type: feature request
