### ISSUE TITLE
[Ruby] Generated code and doc classes for protos should honor ruby_package

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2525] opened 2019-01-23 20:00 UTC
If the Ruby namespace is set via `ruby_package`, gapic doesn't recognize it. In particular:
* The gapic generated code tries to reference proto classes via the default namespace. For example, for pubsub v1, `ruby_package` is set to `Google::Cloud::PubSub::V1`, but gapic generated code still tries to reference `Google::Pubsub::V1::Topic` instead of `Google::Cloud::PubSub::V1::Topic`.
* The namespace of the generated documentation classes do not reflect it. For example, for pubsub v1, `ruby_package` is set to `Google::Cloud::PubSub::V1` but the generated documentation classes still list the namespace as `Google::Pubsub::V1`.

**Comment by jbolinger** [comment] 2019-01-23 22:13
@dazuma is this happening when you specify the `ruby_package` in the proto with the same value for `package_name` in the yaml file?

**Comment by dazuma** [comment] 2019-01-23 22:22
@jbolinger Yes it is.

**Comment by jbolinger** [comment] 2019-01-28 18:30
Ugh, I took a quick look and confirmed. It looks like this isn't something that can be fixed with the config. Feel free to upgrade the priority if you'd like us to fix this before the new generator comes online (I imagine this can be worked around but it probably creates large diffs).

**Comment by dazuma** [comment] 2019-01-28 19:09
We can work around it pretty easily with synth scripts, so no, don't worry about fixing it before the new generator comes online. I'll up the priority if that ever turns out not to be the case.

**Comment by vchudnov-g** [comment] 2019-08-05 21:22
There's been no activity on this, so I'm closing this issue. Feel free to re-open if it comes up again.

**Closed by vchudnov-g** 2019-08-05 21:22 UTC
Labels: :rotating_light:, Lang: Ruby, priority: p2, type: bug
