### ISSUE TITLE
Enforce oneofs with client-side validation

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gapic-generator#1061] opened 2017-02-24 00:27 UTC
### What
For an example proto request message:

```proto3
message SeekRequest {
  string subscription = 1;
  oneof target {
    google.protobuf.Timestamp time = 2;
    string snapshot = 3;
  }
}
```

We should enforce in our GAPIC client code that no more than one field in `oneof target` is allowed to be passed into a method.

### Why
We currently allow the service to enforce this, but the quality of the error message returned by the service might vary across APIs. We can do a better, more consistent job of telling the user what they did wrong in our GAPIC client libs.

Some languages might have an even worse status quo. We think Python arbitrarily selects the last field in a `oneof` block that the user specified. This is undefined behavior that appears to work right now, but that we could "break" at some point post-GA. It would be better to tighten this up to be defined behavior.

### Languages
- [ ] NodeJS
- [ ] PHP
- [x] Python (#1069)
- [ ] Ruby

**Comment by bjwatson** [comment] 2017-02-24 00:29
Language leads: if this issue does not apply to you, then please remove the label and bullet point above for your language.

**Comment by garrettjonesgoogle** [comment] 2017-02-24 00:49
We don't put one of fields in parameter lists in Java currently.

**Comment by jmuk** [comment] 2017-02-24 01:53
ProtoBuf.js reports errors when both of `oneof` are specified. I don't think GAPIC layer should do something for Node.

**Comment by jskeet** [comment] 2017-02-24 07:11
Removed C#:

- The protobuf message handles oneof appropriately (it only stores a single value, and remembers which field it's associated with, then serializes appropriately)
- So long as we never create a flattening with more than one field from the oneof in, we'd never be generating anything that leads to a problem

**Comment by bjwatson** [comment] 2017-02-24 15:17
My main concern is that the user either gets a helpful error message when they define more than one field in a oneof block, or that the GAPIC surface for a language makes this impossible.

It sounds like C# is the latter, is that correct @jskeet? @garrettjonesgoogle Is the same true for Java?

@jmuk Is the ProtoBuf.js error message is helpful enough for the user? If so, then I agree we don't need to do anything for Node.

**Comment by jskeet** [comment] 2017-02-24 15:20
Assuming the GAPIC config has been done separately, it is indeed the latter for C#, and I'd assume that's the case for Java too.

**Comment by bjwatson** [comment] 2017-02-24 15:44
@jskeet Do you think you can resolve https://github.com/googleapis/toolkit/issues/1057 without introducing the possibility that multiple field in a `oneof` block can be defined by the user?

**Comment by jskeet** [comment] 2017-02-24 15:46
@bjwatson: I don't understand your comment, I'm afraid - but it's a somewhat separate issue to this one, so should probably be discussed there. Note that while we *could* avoid ever specifying any oneof-related fields in flattenings, that would be bad in terms of usability.

**Comment by bjwatson** [comment] 2017-02-24 16:13
It's actually a concern on both issues, but I think it's easier to discuss in the context of this one. My understanding is that for the proto in my description above, you generate overloaded C# methods like this:

```c#
        public static void CreateAsync(String subscription, google.protobuf.Timestamp time) ...
        public static void CreateAsync(String subscription, String snapshot) ...
```

There's no risk here of the user specifying both `time` and `snapshot`. However, it's not clear to me what you would do if the proto defined both fields to be `string`. For example:

```proto3
  oneof target {
    string time = 2;
    string snapshot = 3;
  }
```

In this case, you cannot overload `CreateAsync()` like this:

```c#
        public static void CreateAsync(String subscription, String time) ...
        public static void CreateAsync(String subscription, String snapshot) ...
```

One way to solve this is to combine them together, but that raises the problem addressed in this issue:

```c#
        public static void CreateAsync(String subscription, String time = null, String snapshot = null) ...
```

I was just wondering what you had in mind to deal with this?

**Comment by jskeet** [comment] 2017-02-24 17:03
We had previously considered creating a `TargetOneof` type, and make that the parameter. You'd then call it with something like:

```csharp
client.CreateAsync(TargetOneof.FromTime(...));
client.CreateAsync(TargetOneof.FromSnapshot(...));
```

Then it's fine to add more fields to the oneof later - nothing needs to change.

**Comment by lukesneeringer** [comment] 2017-02-24 17:11
I can confirm that Python silently ignores one of the arguments:

```python
>>> pubsub_pb2.SeekRequest(subscription='foo', time=ts, snapshot='bar')
subscription: "foo"
time {
  seconds: 1335024000
}
```

**Comment by jmuk** [comment] 2017-02-24 18:12
Okay, that's fair. ProtoBuf.js's error message is indeed not quite friendly: `Error: Illegal value for Message.Field .google.cloud.speech.v1beta1.SyncRecognizeRequest.audio: .google.cloud.speech.v1beta1.RecognitionAudio (Error: Illegal value for Message.Field .google.cloud.speech.v1beta1.RecognitionAudio.content of type bytes: object (proto3 field without field presence cannot be null))`

Another considerations might be the documentation comment -- Node doesn't say any oneof restriction.

**Comment by bjwatson** [comment] 2017-02-24 18:58
@jskeet I see. You're wrapping the parameter to ensure that it's a unique type. That sounds great, and I have not concerns in this regard for C#.

@garrettjonesgoogle @pongad Can you confirm that you're doing the same for Java and Go, or are you doing something different for `oneof`?

@lukesneeringer Thanks for confirming. That's a good question about the cardinality. If we had a way of saying the entire `oneof` block is required in the GAPIC config, then it could have "one of and exactly one of" semantics. However, I don't think that's currently possible, so we have "zero or one of" semantics for all `oneof` blocks. Does this fit your understanding @geigerj and @garrettjonesgoogle?

@jmuk Gross! :) We have a separate [issue](https://github.com/googleapis/toolkit/issues/274) for the documentation concerns.

**Comment by geigerj** [comment] 2017-02-24 19:01
@bjwatson re: cardinality, I agree with your assessment.

**Comment by jskeet** [comment] 2017-02-24 21:19
To be clear - we're not doing that *yet*. That's what our best thinking was back when we were looking at resource names. Implementing that is how we fix #1057.

**Comment by garrettjonesgoogle** [comment] 2017-02-24 21:55
@bjwatson for Java: If someone configures one-of parameters to be flattened, as things stand now, the client would be broken. We are intending on following the strategy that @jskeet mentioned, where a one-of type will be generated and used as the parameter type, so new one-of variants won't break anything.

**Comment by lukesneeringer** [comment] 2017-02-24 23:24
I have a WIP branch [here][1] (just pending unit tests and more testing of pubsub).

Other language leads might want to wait until I get this tested and merged, so they can use `methodConfig.getOneofs()`.

  [1]: https://github.com/lukesneeringer/toolkit/tree/issue-1061-python

**Comment by bjwatson** [comment] 2017-02-24 23:35
@jskeet @garrettjonesgoogle No worries. If you're implementing these one-of types, it sounds like you won't have this issue by time we go GA for the Logging client.

**Comment by bjwatson** [comment] 2017-02-24 23:35
Thanks @lukesneeringer!

**Comment by lukesneeringer** [comment] 2017-02-28 15:56
Python is merged.

**Comment by pongad** [comment] 2017-03-01 02:58
Removed Go. Details below.

Go uses composite literal to initialize the request object. (Example not checked, but shouldn't too far off)
```go
&SeekRequest{
  Subscription: "foo",
  Target: &SeekRequest_Snapshot{
    Snapshot: "bar",
  },
}
```
It is never possible to set the `oneof` multiple times the same way it is impossible to set any field to multiple values.

**Comment by lukesneeringer** [comment] 2017-03-01 15:31
So, you get an exception if you do:

```go
&SeekRequest_Snapshot{
  Snapshot: "bar",
  Time: timestamp,
}
```

**Comment by pongad** [comment] 2017-03-03 00:20
@lukesneeringer That code doesn't compile, because `SeekRequest_Snapshot` type doesn't have a `Time` member. If you want to use a timestamp:

```go
&SeekRequest_Time{
  Time: timestamp,
}
```

Go protobuf essentially created the oneof type for us, so we don't have to.

**Comment by lukesneeringer** [comment] 2017-03-03 15:17
Got it.

**Comment by lukesneeringer** [comment] 2017-03-06 18:14
Python GAPICs with this change are all released. Removing the Python label.

**Comment by eoogbe** [comment] 2017-11-29 01:34
@alexander-fenster @geigerj @michaelbausor Is this still relevant to your languages?

**Comment by geigerj** [comment] 2017-11-29 16:59
I've just confirmed Ruby is in the same situation as Python was before the fix. That is, the proto runtime allows attempting to set multiple subfields of a oneof, and ignores all but the last. As such, I think Ruby should do the same thing as Python for validation.

```
2.2.6 :002 > Google::Protobuf::ListValue.new(values: [string_value: "abc", number_value: 2])
 => <Google::Protobuf::ListValue: values: [<Google::Protobuf::Value: null_value: :NULL_VALUE, number_value: 2.0, string_value: "", bool_value: false, struct_value: nil, list_value: nil>]> 
2.2.6 :003 > Google::Protobuf::ListValue.new(values: [number_value: 2, string_value: "abc"])
 => <Google::Protobuf::ListValue: values: [<Google::Protobuf::Value: null_value: :NULL_VALUE, number_value: 0.0, string_value: "abc", bool_value: false, struct_value: nil, list_value: nil>]> 
```

**Comment by michaelbausor** [comment] 2017-12-06 19:36
PHP is similar to Ruby, and should be fixed in the same way.

**Comment by hzyi-google** [comment] 2020-04-09 01:06
Implementing https://github.com/googleapis/gapic-generator/pull/2516 would solve this issue.

**Comment by hkdevandla** [comment] 2020-06-03 20:56
Obsolete.

**Closed by hkdevandla** 2020-06-03 20:56 UTC
Labels: Lang: NodeJS, Lang: PHP, Lang: Ruby, Status: Acknowledged, status: release blocking, type: feature request
