### ISSUE TITLE
Sphinx finds unexpected indentation in dialogflow docstrings

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator#2157] opened 2018-07-19 17:23 UTC
Currently there are a few docstrings in the generated dialogflow client. (in agents_client.py)

![image](https://user-images.githubusercontent.com/638797/42959451-b5051352-8b3d-11e8-8121-8b4f63ff33f7.png)

These docstrings have unexpected indentation
` dialogflow-python-client-v2/dialogflow_v2/__init__.py:docstring of dialogflow_v2.AgentsClient.import_agent:41:Block quote ends without a blank line; unexpected unindent.`

The screenshot shows the generation undoing a manual change I made to get docs builds passing.

**Comment by vchudnov-g** [comment] 2018-11-07 18:50
@lukesneeringer ping

**Comment by vchudnov-g** [comment] 2018-11-12 18:34
@lukesneeringer ping

**Comment by noahdietz** [comment] 2018-11-19 22:09
@lukesneeringer friendly ping

**Comment by lukesneeringer** [comment] 2018-11-20 18:19
@michaelbausor Is this a result of your previous fixes? (It seems like the timing is roughly right for that.)

**Comment by michaelbausor** [comment] 2018-11-20 18:22
I don't think the problem is related, as it is from July, much earlier than my fixes. But the recent pandoc fix might have *fixed* this problem - I'm not sure.

**Comment by andreamlin** [comment] 2018-11-26 20:13
@crwilcox Is this still an issue?

**Comment by jbolinger** [comment] 2018-12-10 18:22
@lukesneeringer or @michaelbausor any updates on this?

**Comment by landrito** [comment] 2019-01-02 17:58
@lukesneeringer or @michaelbausor any updates?

**Comment by vchudnov-g** [comment] 2019-02-20 19:40
@lukesneeringer Could you provide an update, as per SLO?

**Comment by noahdietz** [comment] 2019-02-25 18:42
@lukesneeringer @michaelbausor any updates on this? Thanks

**Comment by andreamlin** [comment] 2019-03-06 00:53
@crwilcox has this been fixed?

**Comment by jbolinger** [comment] 2019-03-18 16:59
@lukesneeringer or @crwilcox any updates? Is this fixed?

**Comment by michaelbausor** [comment] 2019-03-28 16:39
Closing this out. If it's still a problem, we can reopen.

**Closed by michaelbausor** 2019-03-28 16:39 UTC
Labels: Lang: Python, Priority: P1, Type: Bug, yoshi
